name: Publish

on: 
    workflow_dispatch:
    push:
        branches:
            - main

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - name: LS
              run: ls
            - name: CAT Dockerfile
              run: cat ../Dockerfile
            - id: repositoryName
              uses: ASzc/change-string-case-action@v1
              with:
                string: ${{ github.event.repository.name }}
            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Build and push PRODUCT
              id: docker_build_product
              uses: docker/build-push-action@v2
              with:
                platforms: linux/amd64
                context: ./
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.repositoryName.outputs.lowercase }}:latest
