name: Publish

on: 
    workflow_dispatch:
    push:
        branches:
            - main

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - name: LS
              run: ls
            - name: CAT Dockerfile
              run: cat Dockerfile
            - id: repositoryName
              uses: ASzc/change-string-case-action@v1
              with:
                string: ${{ github.event.repository.name }}
            - name: Build Image and Push
              uses: judahh/dockerBuildAndPublish@main
              with: 
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                name: ${{ steps.repositoryName.outputs.lowercase }}
                production: true
                platforms: linux/amd64
